### ISSUE TITLE
Add MergeSort in C++, Python,  Java

### ISSUE THREAD

**Issue by iamartyaa** [DecodersCommunity/dsa-library#5]
Create a folder MergeSort inside Algorithms and add 3 files of c++, java, python of merge sort.

**Comment by Tejas20-03** [comment]
It will be my Pleasure to work on above issue

**Comment by pratiksrivastava01** [comment]
@iamartyaa can you assign this to me

**Comment by Shuvamrauniyar** [comment]
can you please assign this to me?
I understood the instructions. I can code in all three languages.

**Comment by k6431494** [comment]
@iamartyaa 
Sir, I can create the folder  merge sort inside algorithms and add 3 files of c++, java and python.
can you assign me this project?

**Comment by dhirajmishra98** [comment]
I can contribute in c++, Java. I would like to contribute in this

**Comment by nitesh-147** [comment]
I would like to contribute to this.

**Comment by harshit-sharma-gits** [comment]
@iamartyaa 
I think we should not create issues for everything. Would you take a look at issues #12 and #13 ?

I created them so that people can mention these issues in their PRs (Whatever is applicable)

So, can we close this issue now?
